services:
  - type: web
    name: social-media-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      # Create media directory and set permissions
      mkdir -p media
      chmod -R 755 media
      # Collect static files including media
      python manage.py collectstatic --noinput --clear
      # Ensure media directory has correct permissions
      chmod -R 755 media
    startCommand: gunicorn Social.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: Social.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: 'False'
    plan: free
