# Generated by Django 5.0.1 on 2025-06-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='no_of_likes',
        ),
    ]
